### ISSUE TITLE
emmitting a message to the client side is not working

### ISSUE THREAD

**Issue by Saifrazaa** [Saifrazaa/socket-programming-with-nodeJS#1]
Sir i am getting a problem on client side .i am emitting a message to client side just to append on the custom chat window but  it is not working kindly check this out .

**Comment by khanshakeeb** [comment]
@Saifrazaa sure i will checkout your repo

**Comment by Saifrazaa** [comment]
sir thankss for your kindness but i did it with my whole effort maybe there was a file issue
